### ISSUE TITLE
FTBFS on "ppc64el" and "arm64"

### ISSUE THREAD

**Issue by onlyjob** [shirou/gopsutil#179]
As reported in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=820466

>It looks like the existing
host_linux_arm.go is actually meant for arm64; please recharacterize it
appropriately and add a version suitable for 32-bit ARM (armel/armhf).

_gopsutil_ FTBFS on _ppc64el_ and _arm64_:

~~~~
# github.com/shirou/gopsutil/host
src/github.com/shirou/gopsutil/host/host_linux.go:108: undefined: utmp
src/github.com/shirou/gopsutil/host/host_linux.go:109: invalid expression unsafe.Sizeof(u)
src/github.com/shirou/gopsutil/host/host_linux.go:117: undefined: utmp
~~~~

Please investigate.

**Comment by shirou** [comment]
To support these architectures, we need to know the size of struct via `cgo` on that arch. But sorry, I don't have a ppc64el and a arm64 machine. Do you know some VPS service or something which I can rent temporary?

**Comment by onlyjob** [comment]
We don't have any accessible VMs... Maybe [this page](https://www.debian.org/ports/) can help? I hope it has information you need...

**Comment by tmm1** [comment]
I think https://www.scaleway.com/ has some arm64 VMs available.

You can also use a debian vm on x86, and `apt-get install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libc6-dev-arm64-cross` then `GOARCH=arm64 CC=aarch64-linux-gnu-gcc go build`

I can also run any code on my arm64 cross compiler setup to calculate struct sizes etc if you need.

**Comment by shirou** [comment]
Yes, I use scaleway and update types_linux on `update_host_type_linux` branch. It works on arm64, but code generation fails linux_amd64 environment, and I have not dig deeper yet. I will tackle next week end.

**Comment by shirou** [comment]
@onlyjob I merged #190 and it can run on my ARM64 environment.

But I do not have a ppc64el machine. I am not familiar with FTBFS, but can we skip ppc64el build?
Thanks!

@tmm1 Thank you for your suggestion.

**Comment by onlyjob** [comment]
> I merged #190 and it can run on my ARM64 environment.

Great, thank you. :)

> Can we skip ppc64el build?

No we can't. :(  _ppc64el_ is an official Debian architecture...

**Comment by discordianfish** [comment]
I still can't cross compile it for ARM64:
```
github.com/shirou/gopsutil/host$ GOARCH=arm64 go build
# github.com/shirou/gopsutil/host
./host_linux.go:110: undefined: sizeOfUtmp
./host_linux.go:115: undefined: sizeOfUtmp
./host_linux.go:117: undefined: utmp
```

But GOARCH=arm works fine. And there might be some confusion: _arm64.go should get compiled on GOARCH=arm64 and _arm.go on GOARCH=arm, which explains why I can compile it for arm but not arm64.

Now I'm not sure what the right values for each arch are but currently there is only a definition for arm but non for arm64, hence it's not compiling.

From playing around with `cgo -godefs` it seems to honor GOARCH/GOOS, so I created a definition and will submit a PR in a sec.

**Comment by shirou** [comment]
@onlyjob @discordianfish I'm very sorry! I made a big mistake!!

I used [scaleway](https://www.scaleway.com/) to check ARM64. I haven't know that, but scaleway is arm7 and arm7 is 32 bit! 
Now I got a Raspberry Pi 3. It might be 64bit. I will create ARM64 files in a few week. please be patient.

**Comment by tmm1** [comment]
@shirou The rpi3 is only 32-bit also. I recommend you use the cross-compiler on any ubuntu machine to test aarch64 support.

**Comment by discordianfish** [comment]
@shirou See my PR, I've created definitions for arm64. Haven't tested it though. Will try that now.

**Comment by shirou** [comment]
@tmm1 OK, I understand. rpi3 has 64 bit CPU but Raspbian 64 bit is not officially released yet. So, I will merge @discordianfish 's PR. Thank you for your conversation and contribution!
